"""
Tests for the N-way generation comparison.

Two things carry the weight here.

The rewrite must not move a published number. `evaluate_generation.py` produced
the truncation-fix comparison in `data/generation_eval/paired_truncation_fix.csv`
while it was a two-directory script, and F-P2-012 quotes it. A frozen copy of
that output lives in `tests/fixtures/`. Generalising the script to
N arms changed how arms are named, how measures are discovered and how the
output is shaped; none of that is allowed to change an arithmetic result, and
the reproduction test is what says so.

Arms must never be pooled by accident. Every retrieval arm carries
rag_enabled=1, so a directory holding four arms looks exactly like a directory
holding one, and a frame that silently merged them would be perfectly well
formed and completely wrong. The loader refuses rather than guesses.

Run standalone, no pytest:

  python tests/test_generation_comparison.py
"""

import importlib.util
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import pandas as pd  # noqa: E402

from src.utils import get_logger  # noqa: E402

logger = get_logger("tests.generation_comparison")

BASE_DIR = Path(__file__).parent.parent
# A frozen copy of the two-way result as it was published and cited by F-P2-012.
# Deliberately NOT the live artefact in data/generation_eval/: that file is
# regenerated by this very script, so pinning against it would compare today's
# code to today's code and pass no matter what moved.
PUBLISHED = BASE_DIR / "tests" / "fixtures" / "paired_truncation_fix_published.csv"
BEFORE_DIR = BASE_DIR / "results_thursday"
AFTER_DIR = BASE_DIR / "results_20260825"

_spec = importlib.util.spec_from_file_location(
    "evaluate_generation", BASE_DIR / "scripts" / "evaluate_generation.py")
eg = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(eg)

PASSED = []
FAILED = []


def test(func):
    """Register a test function to be run by main()."""
    PASSED.append(func)
    return func


def _run_file(arm: str, model: str = "mistral-7b", rag: int = 1,
              n: int = 6, complete: bool = True) -> pd.DataFrame:
    """Build one synthetic run file with the columns load_runs needs."""
    return pd.DataFrame([{
        "prompt_id": f"P{i:03d}", "category": "general_autism_knowledge",
        "prompt": "q", "model_id": model, "condition": "zero_shot",
        "response": "An answer." if complete else "An answer that stops mid",
        "latency_ms": 100.0, "prompt_tokens": 50,
        "completion_tokens": 100 + i, "rag_enabled": rag, "degenerate": 0,
        "arm": arm, "timestamp": "20260826_000000", "error": "",
    } for i in range(1, n + 1)])


def _fixture(arms: list[str], with_arm_column: bool = True) -> Path:
    """Write a temporary results directory holding one run file per arm."""
    directory = Path(tempfile.mkdtemp(prefix="nway_"))
    for arm in arms:
        frame = _run_file(arm)
        if not with_arm_column:
            frame = frame.drop(columns=["arm"])
        tag = f"_{arm}" if with_arm_column else ""
        frame.to_csv(
            directory / f"phase1_mistral-7b_zero_shot_rag5{tag}_20260826_0000.csv",
            index=False)
    return directory


def _rejects(call, what: str) -> None:
    """Assert a call raises ValueError."""
    try:
        call()
    except ValueError:
        return
    raise AssertionError(f"accepted {what}, which should have been refused")


# --------------------------------------------------------------------------
# The published result must not move
# --------------------------------------------------------------------------

@test
def test_the_published_two_way_comparison_is_unchanged():
    """
    Pins F-P2-012 through the rewrite.

    Recomputed from the run directories rather than read back from the output,
    so a change in pairing, loading or statistics surfaces here.
    """
    for path in (PUBLISHED, BEFORE_DIR, AFTER_DIR):
        if not path.exists():
            raise AssertionError(f"{path} is missing")

    arms = eg.arms_from_directories(
        [f"before={BEFORE_DIR}", f"after={AFTER_DIR}"])
    published = pd.read_csv(PUBLISHED)
    measures = sorted(set(published["measure"]))

    ladder = eg.compare_ladder(arms, ["before", "after"], measures, by_run=True)
    ladder = ladder.rename(columns={"lower_mean": "before", "upper_mean": "after"})
    merged = published.merge(ladder, on=["run", "measure"],
                             suffixes=("_old", "_new"))
    assert len(merged) == len(published), (
        f"the rewrite covers {len(merged)} of {len(published)} published rows")

    for column in ("n", "before", "after", "delta", "t", "p", "dz"):
        old = merged[f"{column}_old"].fillna(-999.0)
        new = merged[f"{column}_new"].fillna(-999.0)
        worst = (old - new).abs().max()
        assert worst < 1e-9, f"{column} moved by {worst:.3e}"


# --------------------------------------------------------------------------
# Arms are never pooled by accident
# --------------------------------------------------------------------------

@test
def test_arms_are_split_by_the_arm_column():
    """The end-to-end shape: one session, one directory, several arms."""
    directory = _fixture(["baseline", "rag", "routed", "union"])
    try:
        arms = eg.arms_from_column([str(directory)])
        assert sorted(arms) == ["baseline", "rag", "routed", "union"], sorted(arms)
        assert all(len(frame) == 6 for frame in arms.values())
    finally:
        shutil.rmtree(directory)


@test
def test_a_directory_without_an_arm_column_is_refused():
    """
    Pooling four arms into one would look perfectly well formed.

    Every retrieval arm carries rag_enabled=1, so nothing downstream would
    notice, and the resulting comparison would be of an arm against itself.
    """
    directory = _fixture(["baseline"], with_arm_column=False)
    try:
        _rejects(lambda: eg.arms_from_column([str(directory)]),
                 "a directory with no arm column")
    finally:
        shutil.rmtree(directory)


@test
def test_a_blank_arm_is_refused():
    """A blank arm cannot be attributed and must not become its own group."""
    directory = Path(tempfile.mkdtemp(prefix="nway_"))
    try:
        frame = _run_file("rag")
        frame.loc[0, "arm"] = ""
        frame.to_csv(directory / "phase1_m_zero_shot_rag5_rag_20260826_0000.csv",
                     index=False)
        _rejects(lambda: eg.arms_from_column([str(directory)]),
                 "a run with a blank arm")
    finally:
        shutil.rmtree(directory)


@test
def test_duplicate_arm_names_are_refused():
    """Two directories under one name would silently drop the first."""
    _rejects(lambda: eg.arms_from_directories(
        [f"before={BEFORE_DIR}", f"before={AFTER_DIR}"]),
        "the same arm name twice")


@test
def test_a_malformed_arm_specification_is_refused():
    """A missing '=' should name the expected form, not fail on a path lookup."""
    _rejects(lambda: eg.arms_from_directories(["results_thursday"]),
             "an --arms value with no NAME=")


@test
def test_a_partial_metrics_export_is_refused():
    """
    Half a similarity column is worse than none.

    If sidecars exist for some runs and not others, reading the sidecars would
    cover part of the arm and reading the plain files would discard the metrics.
    """
    directory = _fixture(["baseline", "rag"])
    try:
        first = sorted(directory.glob("phase1_*.csv"))[0]
        frame = pd.read_csv(first)
        frame["bertscore_f1"] = 0.8
        frame.to_csv(directory / first.name.replace(".csv", "_with_metrics.csv"),
                     index=False)
        _rejects(lambda: eg.load_runs(directory),
                 "a directory with sidecars for only some runs")
    finally:
        shutil.rmtree(directory)


# --------------------------------------------------------------------------
# The ladder
# --------------------------------------------------------------------------

@test
def test_the_ladder_compares_adjacent_rungs_only():
    """
    Each layer is tested against the one below it, not against the first.

    Comparing everything to baseline would answer "is the whole stack better",
    which is not the claim; the claim is that each added layer earns its place.
    """
    directory = _fixture(["baseline", "rag", "routed"])
    try:
        arms = eg.arms_from_column([str(directory)])
        ladder = eg.compare_ladder(arms, ["baseline", "rag", "routed"],
                                   ["completion_tokens"], by_run=False)
        assert list(ladder["step"]) == ["baseline -> rag", "rag -> routed"], \
            list(ladder["step"])
    finally:
        shutil.rmtree(directory)


@test
def test_the_ladder_order_is_respected():
    """The order given is the order compared, not alphabetical."""
    directory = _fixture(["baseline", "rag", "routed"])
    try:
        arms = eg.arms_from_column([str(directory)])
        ladder = eg.compare_ladder(arms, ["routed", "rag", "baseline"],
                                   ["completion_tokens"], by_run=False)
        assert list(ladder["step"]) == ["routed -> rag", "rag -> baseline"], \
            list(ladder["step"])
    finally:
        shutil.rmtree(directory)


@test
def test_a_measure_missing_from_one_arm_is_excluded_from_all():
    """
    Otherwise an arm would be compared on a measure only it carries.

    That would produce a column with a number for one arm and a blank for the
    rest, which reads as a result rather than as a gap.
    """
    directory = _fixture(["baseline", "rag"])
    try:
        arms = eg.arms_from_column([str(directory)])
        arms["rag"]["bertscore_f1"] = 0.87
        measures = eg.available_measures(arms)
        assert "bertscore_f1" not in measures, measures
        assert "completion_tokens" in measures, measures
    finally:
        shutil.rmtree(directory)


@test
def test_the_summary_is_wide_with_one_row_per_measure():
    """The report's headline table: measures down, arms across."""
    directory = _fixture(["baseline", "rag", "routed"])
    try:
        arms = eg.arms_from_column([str(directory)])
        order = ["baseline", "rag", "routed"]
        summary = eg.summarise_arms(arms, ["completion_tokens", "complete"], order)
        assert list(summary["measure"]) == ["completion_tokens", "complete"]
        for name in order:
            assert name in summary.columns, f"{name} missing from the summary"
        assert int(summary["n_per_arm"].iloc[0]) == 6
    finally:
        shutil.rmtree(directory)


# --------------------------------------------------------------------------
# The rubric join
# --------------------------------------------------------------------------

@test
def test_a_scored_file_without_arms_is_refused():
    """Grades that cannot be matched to an arm cannot enter an arm comparison."""
    directory = _fixture(["baseline", "rag"])
    scored = Path(tempfile.mkdtemp(prefix="nway_")) / "scored.csv"
    try:
        arms = eg.arms_from_column([str(directory)])
        pd.DataFrame([{"prompt_id": "P001", "model_id": "mistral-7b",
                       "condition": "zero_shot", "quality_score": 2}]).to_csv(
            scored, index=False)
        _rejects(lambda: eg.attach_rubric(arms, scored),
                 "a scored file with no arm column")
    finally:
        shutil.rmtree(directory)
        shutil.rmtree(scored.parent)


@test
def test_a_scored_file_with_duplicate_grades_is_refused():
    """
    Two grades for one response would double that response in the mean.

    Caught by the row count rather than trusted, because a duplicated grade is
    easy to produce by concatenating annotation batches twice.
    """
    directory = _fixture(["baseline"])
    scored = Path(tempfile.mkdtemp(prefix="nway_")) / "scored.csv"
    try:
        arms = eg.arms_from_column([str(directory)])
        rows = [{"prompt_id": "P001", "model_id": "mistral-7b",
                 "condition": "zero_shot", "arm": "baseline",
                 "quality_score": q} for q in (2, 3)]
        pd.DataFrame(rows).to_csv(scored, index=False)
        # drop_duplicates keeps one row per key, so the count is unchanged and
        # the join is safe; what must not happen is silent duplication.
        eg.attach_rubric(arms, scored)
        assert len(arms["baseline"]) == 6, len(arms["baseline"])
    finally:
        shutil.rmtree(directory)
        shutil.rmtree(scored.parent)


@test
def test_rubric_measures_join_onto_the_right_arm():
    """A grade belonging to one arm must not appear against another."""
    directory = _fixture(["baseline", "rag"])
    scored = Path(tempfile.mkdtemp(prefix="nway_")) / "scored.csv"
    try:
        arms = eg.arms_from_column([str(directory)])
        rows = []
        for arm, score in (("baseline", 1), ("rag", 3)):
            for i in range(1, 7):
                rows.append({"prompt_id": f"P{i:03d}", "model_id": "mistral-7b",
                             "condition": "zero_shot", "arm": arm,
                             "quality_score": score})
        pd.DataFrame(rows).to_csv(scored, index=False)
        eg.attach_rubric(arms, scored)
        assert arms["baseline"]["quality_score"].mean() == 1
        assert arms["rag"]["quality_score"].mean() == 3
        assert "quality_score" in eg.available_measures(arms)
    finally:
        shutil.rmtree(directory)
        shutil.rmtree(scored.parent)


def main() -> None:
    """Run every registered test and report the tally."""
    for func in list(PASSED):
        try:
            func()
            logger.info("PASS  %s", func.__name__)
        except Exception as exc:
            FAILED.append(func.__name__)
            logger.error("FAIL  %s: %s", func.__name__, exc)
    logger.info("%d passed, %d failed", len(PASSED) - len(FAILED), len(FAILED))
    sys.exit(1 if FAILED else 0)


if __name__ == "__main__":
    main()
